insert into Chronic(ChronicId, ChronicName, OrderBy) values(1, 'Cancer', 1);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(2, 'Diabetes', 2);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(3, 'HeartDisease',3 );
insert into Chronic(ChronicId, ChronicName, OrderBy) values(4, 'Highbloodpressure',4);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(5, 'Highcholesterol',5);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(6, 'Asthma',6);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(7, 'COPD',7);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(8, 'Stroke',8);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(9, 'Arthritis',9);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(10, 'Hypothyroidism',10);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(11, 'Hyperthyroidism',11);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(12, 'Pregnancy',12);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(13, 'Chronicrenaldisease',13);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(14, 'Crohnsdisease',14);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(15, 'Epilepsy',15);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(16, 'Osteoporosis',16);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(17, 'Rheumatoidarthritis',17);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(18, 'Ulcerativecolitis',18);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(19, 'Alzheimer',19);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(20, 'Parkinsonsdisease',20);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(21, 'Multiplesclerosis',21);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(22, 'Bipolarmooddisease',22);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(23, 'EatingDisorder',23);
insert into Chronic(ChronicId, ChronicName, OrderBy) values(-1, 'OtherChronicIllness',24);